// <auto-generated />
namespace eljur_notifier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_struct1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_struct1));
        
        string IMigrationMetadata.Id
        {
            get { return "201812191701034_change_struct1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
