//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eljur_notifier.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dfdssdfsfDFsfdsdgsdffWe52345EDFsd")]
        public string EljurApiTocken {
            get {
                return ((string)(this["EljurApiTocken"]));
            }
            set {
                this["EljurApiTocken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900000")]
        public double FrenchLeaveInterval {
            get {
                return ((double)(this["FrenchLeaveInterval"]));
            }
            set {
                this["FrenchLeaveInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8677")]
        public int ConfigsTreeIdResourceInput1 {
            get {
                return ((int)(this["ConfigsTreeIdResourceInput1"]));
            }
            set {
                this["ConfigsTreeIdResourceInput1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9256")]
        public int ConfigsTreeIdResourceInput2 {
            get {
                return ((int)(this["ConfigsTreeIdResourceInput2"]));
            }
            set {
                this["ConfigsTreeIdResourceInput2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"          
          User=SYSDBA;
          Password=masterkey;
          Database=D:/School/Backup_PERCo_04.10.18/Backup_PERCo_04.10.18/4.10.18_9.23/NEWBASE.FDB;
          Port=3050;
          Dialect=3;
          Charset=WIN1251;
          Role=;
          Connection lifetime=30;
          Pooling=true;
          MinPoolSize=0;
          MaxPoolSize=50;
          Packet Size=8192;
          ServerType=0;
        ")]
        public string ConStrFirebird {
            get {
                return ((string)(this["ConStrFirebird"]));
            }
            set {
                this["ConStrFirebird"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public double IntervalRequest {
            get {
                return ((double)(this["IntervalRequest"]));
            }
            set {
                this["IntervalRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120000")]
        public double IntervalSleepBeforeReset {
            get {
                return ((double)(this["IntervalSleepBeforeReset"]));
            }
            set {
                this["IntervalSleepBeforeReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8564")]
        public int ConfigsTreeIdResourceOutput1 {
            get {
                return ((int)(this["ConfigsTreeIdResourceOutput1"]));
            }
            set {
                this["ConfigsTreeIdResourceOutput1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9369")]
        public int ConfigsTreeIdResourceOutput2 {
            get {
                return ((int)(this["ConfigsTreeIdResourceOutput2"]));
            }
            set {
                this["ConfigsTreeIdResourceOutput2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23:57:59")]
        public global::System.TimeSpan timeFromDel {
            get {
                return ((global::System.TimeSpan)(this["timeFromDel"]));
            }
            set {
                this["timeFromDel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23:59:59")]
        public global::System.TimeSpan timeToDel {
            get {
                return ((global::System.TimeSpan)(this["timeToDel"]));
            }
            set {
                this["timeToDel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000")]
        public double IntervalDel {
            get {
                return ((double)(this["IntervalDel"]));
            }
            set {
                this["IntervalDel"] = value;
            }
        }
    }
}
